### PR TITLE
updated strimzi version

### PR DESCRIPTION
**Pull request by franvila**
### Type of change

- Enhancement / new feature

### Description

Update the strimzi version to be up to date. Systems tests are passing.

### Checklist

- [ ] Write tests
- [X] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Comment by franvila** [comment]
@strimzi-ci run system tests

**Review by k-wall — APPROVED** [review]
lgtm

**Comment by franvila** [comment]
@strimzi-ci run system tests

**Comment by franvila** [comment]
@strimzi-ci run system tests

**Comment by franvila** [comment]
@strimzi-ci run system tests

**Comment by franvila** [comment]
@strimzi-ci run system tests

**Comment by franvila** [comment]
@strimzi-ci run system

**Comment by franvila** [comment]
@strimzi-ci run systemtests

**Comment by franvila** [comment]
@strimzi-ci run systemtests

**Comment by franvila** [comment]
@strimzi-ci run system tests

**Comment by franvila** [comment]
@strimzi-ci run system tests

**Pull request merged**
