### PR TITLE
Rename FilterResult to FilterCommand

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Refactoring

### Description

Why:
Result sounds like a common pattern of value-or-exception. A term like Command captures better that it's a desired action the Filter wants enacted. The Filter is commanding the Kroxylicious framework to do something, forward a message or close the connection etc. It's up to the framework to then execute that intent or handle failure if it can't do it.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Review by SamBarker — COMMENTED** [review]
I totally agree with your rational for the change @robobario however I'm not convinced by `RequestFilterCommand` and `RequestFilterCommand` as the new names. They sound to me like the commands one would issue to create the filters rather than as the outcome. 

Having said that I haven't come up with a name that works better for me either.

**Comment by robobario** [comment]
Gets verbose but does `MessageFilterCommand`, `RequestMessageFilterCommand`, `ResponseMessageFilterCommand` describe it better?

**Comment by robobario** [comment]
Another idea, maybe the naming is hard since we are using the one interface to capture myriad commands. Maybe it'd be easier to name if it was more like:

```
sealed Command(closeConnection: boolean) {
     ForwardRequestCommand(RequestHeaderData header, ApiMessage body)
     ForwardResponseCommand(RequestHeaderData header, ApiMessage body)
     ShortCircuitResponseCommand(RequestHeaderData header, ApiMessage body)
     DropCommand()
}
```

**Comment by SamBarker** [comment]
> Another idea, maybe the naming is hard since we are using the one interface to capture myriad commands. Maybe it'd be easier to name if it was more like:
> 
> ```
> sealed Command(closeConnection: boolean) {
>      ForwardRequestCommand(RequestHeaderData header, ApiMessage body)
>      ForwardResponseCommand(ResponseHeaderData header, ApiMessage body)
>      ShortCircuitResponseCommand(ResponseHeaderData header, ApiMessage body)
>      DropCommand()
>      CloseCommand()
> }
> ```

Give or take the inner Command that does seem more like it. 

```
 sealed Command(closeConnection: boolean) {
      ForwardRequest(RequestHeaderData header, ApiMessage body)
      ForwardResponse(ResponseHeaderData header, ApiMessage body)
      ShortCircuitResponse(ResponseHeaderData header, ApiMessage body)
      Drop()
      Close()
 }
 ```

**Comment by robobario** [comment]
but also more of a refactor to get there, will wait for Keith to comment on Friday to see what he thinks

**Comment by robobario** [comment]
I do like that the current API are interfaces though

**Comment by robobario** [comment]
> I totally agree with your rational for the change @robobario however I'm not convinced by RequestFilterCommand and RequestFilterCommand as the new names. They sound to me like the commands one would issue to create the filters rather than as the outcome.

>  Returning something named Command doesn't feel quite right. How about Action ?

Does Action work sound good to you @SamBarker? `FilterAction`, `RequestFilterAction`, `ResponseFilterAction`? I'm happy with that.

**Comment by SamBarker** [comment]
> > I totally agree with your rational for the change @robobario however I'm not convinced by RequestFilterCommand and RequestFilterCommand as the new names. They sound to me like the commands one would issue to create the filters rather than as the outcome.
> 
> 
> 
> >  Returning something named Command doesn't feel quite right. How about Action ?
> 
> 
> 
> Does Action work for you @SamBarker? `FilterAction`, `RequestFilterAction`, `ResponseFilterAction`? I'm happy with that.

I have bigger problems with the prefix than the suffix I still read `RequestFilterAction` as something that wants request filter to be actioned rather than as something that comes as a result of `*RequestFilter` being invoked.

**Comment by robobario** [comment]
A little unconventional but does `FilterAction`, `FilterRequestAction`, `FilterResponseAction` work better?

**Comment by robobario** [comment]
I think I'm almost back to preferring the Result naming :grin:  given the ambiguity between:

1. the work done by the Filter (could be natural for an author to think of this as the Filter Action)
2. what should be done after the Filter's work is finished

I put it in the agenda for our call to figure out where we want to go.

**Comment by k-wall** [comment]
I'm not going to stand in the way, but the name "Result" is good enough for me.

**Comment by robobario** [comment]
Yep I'm happy Result is good enough too, thanks.

**Pull request closed without merging**
