### PR TITLE
Bash best practice - use command -v over which in scripts.

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Refactoring

### Description

Use `command -v` over `which`

### Additional Context

Why - the former is consider better practice.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Review by SamBarker — APPROVED** [review]
LGTM

Thanks @k-wall

**Review by robobario — APPROVED** [review]
LGTM

**Comment by SamBarker** [comment]
For the record I have tested the change on both Mac OS and Fedora. `command -v` and `which` behave the same however the script fails silently if any of the dependencies are missing.

**Review by gracegrimwood — APPROVED** [review]
LGTM! 👍

**Comment by SamBarker** [comment]
sorry @k-wall I didnt mean to push changes to your PR, intellij defaulted to your remote and I didn't notice....

**Comment by k-wall** [comment]
Being replaced by #440

**Pull request closed without merging**
