### PR TITLE
Extract kafka record batch transformation into re-usable module

### LINKED ISSUE #1127: Offer record transformation convenience as a public API
As part of implementing Record Encryption we have introduced some abstractions for manipulating Records in Produce Requests and Fetch Responses while preserving batching and batch metadata.

[RecordStream](https://github.com/kroxylicious/kroxylicious/blob/a1bb61c5ec273c1154e554cef667b20318afd044/kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/records/RecordStream.java)
[RecordTransform](https://github.com/kroxylicious/kroxylicious/blob/main/kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/records/RecordTransform.java)
[BatchAwareMemoryRecordsBuilder](https://github.com/kroxylicious/kroxylicious/blob/a1bb61c5ec273c1154e554cef667b20318afd044/kroxylicious-filters/kroxylicious-record-encryption/src/main/java/io/kroxylicious/filter/encryption/records/BatchAwareMemoryRecordsBuilder.java)

A single MemoryRecords of topic-partition data can be comprised of multiple batches. Each batch has some metadata. There are some special cases to consider like batches that have had 100% of their records removed and control batches that carry control messages like transaction commit/rollbacks. For the proxy to act transparently we want to ensure messages remain batched the same way and these special batches are preserved.

Making this functionality available to users as part of a public API should enable them to implement message transforms safely without having to rediscover how to work with batches (which is a bit ugly as we discovered, requiring the BatchAwareMemoryRecordsBuilder to build multi-batch MemoryRecords)

### PR DESCRIPTION
**Pull request by robobario**
Resolves #1127

### Type of change

- Enhancement / new feature

### Description

Creates a kroxylicious-kafka-message-tools module for classes that are purely interested in manipulating the classes in kafka-clients independent of any proxy behaviour.

This should allow user filters to use the behaviour but enable them to use a kroxylicious-kafka-message-tools version independent of the kroxylicious version. (caveat that since kroxylicious-kafka-message-tools depends on kafka-clients and kafka-clients can change, a version of kroxylicious-kafka-message-tools could become incompatible with a newer version of kroxylicious if the proxie's kafka-clients version is incompatible).

The first behaviour added to this module is record transformation. That is we want to enable filters to mutate the records contained in fetch and produce requests while preserving how the records are batched inside their MemoryRecords along with all the batch metadata.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Comment by tombentley** [comment]
I think this might need fixing now that the layering in the encryption filter PR has been merged. But I'm +1 on this.

**Comment by tombentley** [comment]
We shouldn't be using the encryption package as the package in the new module, we should be using something unique to the new module, like `io.kroxylicious.utils.records`, or something.

**Comment by SamBarker** [comment]
[Proxy-sync] Need to add some checkstyle rules to ensure we don't pull in kroxylicious-api and kroxylicious-api doesn't pull this.

**Review by SamBarker — COMMENTED** [review]
I think this will be useful just need to re-name the packages as @tombentley mentioed

**Pull request merged**
