### PR TITLE
Cancel the timeout future when request is sent

### PR DESCRIPTION
**Pull request by luozhenyu**
### Type of change

- Bugfix

### Description

The timeout exception is called whether the filter promise completes normally or not. A timeout log will be printed at debug level.

No exception will be thrown for now, because `completeExceptionally` just returns false instead of throwing an exception if the future is completed

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Review by SamBarker — APPROVED** [review]
Thanks  @luozhenyu The change itself looks good to me and does the right thing.

That said I'm a bit disappointed by the fact this change isn't testable so I'm starting a branch to try and improve the test coverage around this.

**Review by k-wall — APPROVED** [review]
lgtm

**Comment by k-wall** [comment]
@SamBarker I'm wondering if this should be in an 0.5.1.

**Comment by SamBarker** [comment]
AS mentioned my testing branch/PR is https://github.com/kroxylicious/kroxylicious/pull/1129

@k-wall do you really think it needs a change log entry? I guess it removes spurious logging that would mislead users so maybe it does motivate a 0.5.1 release.

**Comment by k-wall** [comment]
> AS mentioned my testing branch/PR is #1129
> 
> @k-wall do you really think it needs a change log entry? I guess it removes spurious logging that would mislead users so maybe it does motivate a 0.5.1 release.

Yes, I think it does.

**Comment by k-wall** [comment]
In the end we opted for a refactor that allowed this fix to be verified by unit test.  The fix is incorporated into #1129.

**Pull request closed without merging**
