### PR TITLE
Remove deprecated CompositeFilter and it's documentation

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Improvement/Documentation

### Description

We deprecated CompositeFilter in 0.3.0, feeling like it wasn't adding value compared to using composable behaviours within a Filter to get the same result.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Review by tombentley — COMMENTED** [review]
This makes me think we should aim to have docs for each version available on the website, so people can refer to the docs for the version they're using, even if it's no longer the current version.

Did we decide when to remove the CompositeFilter itself?

**Comment by robobario** [comment]
> Did we decide when to remove the CompositeFilter itself?

No, it's `@Deprecated(since = "0.3.0", forRemoval = true)` and we've never got back to cleaning up that and a number of other Deprecated classes. Happy to extend this to killing the whole CompositeFilter if that's more sensible to have it go in one lump.

**Comment by tombentley** [comment]
That seems reasonable to me, personally.

**Review by k-wall — APPROVED** [review]

**Review by k-wall — APPROVED** [review]
lgtm, thank you @robobario

**Pull request merged**
