### PR TITLE
Annotations

### PR DESCRIPTION
**Pull request by tombentley**
### Type of change

- Refactoring

### Description

This PR factors out a new `kroxylicious-annotations` module, which currently contains only the `@VisibleForTesting` annotation. This allows to use this annotation outside just the runtime (for example, in filters). In the future this module can also be used for other similar annotations, as we see fit.

### CODE REVIEW

**Review by SamBarker — APPROVED** [review]
Two thoughts. 

- Is it really independent of `kroxylicious-api`? 
- I like `VisibleForTesting` as a name, but a little concerned about the clash with the more common Guava version. Should use `ExposedForTesting` to avoid the naming clash and breaking peoples brains.

**Comment by tombentley** [comment]
> Two thoughts.
> 
>  * Is it really independent of `kroxylicious-api`?

That's a good question. I'm not sure what the right answer is. 

On the one hand, I think that would work. On the other hand, putting everything common in the `-api` means lots of things grow that dependency even if they only need a sliver of the functionality. And this provides a nice example: If you want to add a purely documentary annotation you would have to depend on the whole API module, which obscures just how narrow the dependency truly is. The Vault KMS provider another example: It depends on the api even though it doesn't provide a filter implementation. Rather it depends on some config classes and `@Plugin` (which is more like an SPI than an API). Having those packages all in -api allows quite distinct responsibilities to become accidentally interdependent.

I admit that I can't point to an irrefutable counterexample for why we _must_ have a separate module. But it does _feel_ like moving in the direction of finer-grained dependencies would be cleaner and might simplify things in the longer term.
 
>  * I like `VisibleForTesting` as a name, but a little concerned about the clash with the more common Guava version. Should use `ExposedForTesting` to avoid the naming clash and breaking peoples brains.

:shrug: so Guava chose another name. I don't feel the need to ape their naming. We're using this annotation to express something about _visibility_ (`public`, `protected`, `private` are almost always called the "visibility modifiers", I've never heard them called "exposure modifiers"), so using visible seems better to me.

**Comment by SamBarker** [comment]
> 🤷 so Guava chose another name. I don't feel the need to ape their naming.

No guava chose the same name hence the cognitive clash. As you say it's the right name.

**Comment by SamBarker** [comment]
I'm happy with a separate module, has to start somewhere. Smaller more compostable does feel like the right move.

**Comment by tombentley** [comment]
> No guava chose the same name hence the cognitive clash. As you say it's the right name.

Ah, sorry I misread/misunderstood your point!

**Pull request merged**
