### PR TITLE
use netty-leak-detector-junit-extension

### PR DESCRIPTION
**Pull request by sullis**
### Type of change

- Refactoring

### Description

use [netty-leak-detector-junit-extension](https://github.com/nettyplus/netty-leak-detector-junit-extension) for Netty leak detection

### Additional Context

this is a more generalized way of detecting Netty resource leaks

### Netty resource leaks

https://speakerdeck.com/sullis/netty-chicago-java-user-group-2024-04-17

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Review by SamBarker — COMMENTED** [review]
Thanks for the PR @sullis I really like the extension. However I think it needs https://github.com/sullis/kroxylicious/pull/1 to get the kroxylicious build working

**Comment by sullis** [comment]
> Thanks for the PR @sullis I really like the extension. However I think it needs [sullis#1](https://github.com/sullis/kroxylicious/pull/1) to get the kroxylicious build working

Merged.

**Comment by SamBarker** [comment]
Sorry my bad @sullis we also need https://github.com/sullis/kroxylicious/pull/2 apparently I didn't read enough log output before opening https://github.com/sullis/kroxylicious/pull/1

**Comment by sullis** [comment]
> Sorry my bad @sullis we also need [sullis#2](https://github.com/sullis/kroxylicious/pull/2) apparently I didn't read enough log output before opening [sullis#1](https://github.com/sullis/kroxylicious/pull/1)

Merged.

**Review by SamBarker — APPROVED** [review]
LGTM 

Thanks @sullis

**Pull request merged**
