### PR TITLE
Add github action to build and deploy container images to quay.io

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Enhancement / new feature

### Description

This runs in reaction to a pushed vX.Y.Z tag and builds the docker image, pushing it to `quay.io/kroxylicious/kroxylicious-development:${versionFromPomXml}` It builds amd64 and arm64 images for the tag. It can also be triggered via the github UI.

### Additional Context

Users will want a way to run kroxylicious on docker, we can offer a public image and users can build on top of it or mount in their custom filter jars.

This will also enable us to explore things like writing an operator in a separate repo to deploy/configure kroxylicious.

### CODE REVIEW

**Comment by robobario** [comment]
The repository is created and quay secrets are configured into this repositories github settings, I tried the manual action flow on my fork and got it to publish successfully to my quay account with cross-platform docker images.

**Review by k-wall — APPROVED** [review]
lgtm

**Review by SamBarker — APPROVED** [review]
I'm not sold on using the current container build for production use cases but name the published artefact `kroxylicious-developer` or `kroxylicious-testing` or some such and I'm sold.

**Comment by robobario** [comment]
Will rename it to something less official sounding.

**Pull request merged**
