### PR TITLE
re-use the secureRandom between invocations of Aes.paramSupplier.

### PR DESCRIPTION
**Pull request by SamBarker**
### Type of change

_Select the type of your PR_

- Enhancement / new feature
- Refactoring

### Description

Shared secure random between invocations to avoid repeated costly initialisations

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Comment by tombentley** [comment]
@strimzi-ci run perf

**Review by k-wall — APPROVED** [review]

**Comment by SamBarker** [comment]
@strimzi-ci run perf

**Comment by tombentley** [comment]
Those numbers make this look like a perf regression, no?

**Comment by SamBarker** [comment]
they look within the realms of normal variation we see between runs.

**Pull request merged**
