### PR TITLE
Improve kroxylicious startup ascii art

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Enhancement / new feature

### Description

Kroxylicious writes an ascii art kroxylicious icon into the logs on startup.  It doesn't look too slick.  I wondered if it could be improved.

_Please describe your pull request_

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Comment by k-wall** [comment]
This is the work of @insectengine

**Comment by k-wall** [comment]
@insectengine thank you, that's definitely much easier on the eye.
It is possible to make it smaller?

Screenshot 2024-02-07 at 12 36 28

**Comment by insectengine** [comment]
the previous one was 90 spaces wide. I've worked up two at 40 spaces.

Screenshot 2024-02-07 at 9 26 28 AM

**Comment by insectengine** [comment]
[kroxy_symbols_ascii.txt](https://github.com/kroxylicious/kroxylicious/files/14195832/kroxy_symbols_ascii.txt)
[kroxy_block_ascii.txt](https://github.com/kroxylicious/kroxylicious/files/14195834/kroxy_block_ascii.txt)

**Comment by k-wall** [comment]
@insectengine thank you.

Of the two 40 width versions, the block ascii is more pleasing on the eye.  However, I don't know how universal support is for Extended ASCII in all terminal emulators. A google shows some  reports of users reporting issues, but these all seemed to be 15+years old.  Maybe I'm worrying about nothing.

I do like the smoother look of the 90 width version (but would drop the ASCII art "Kroxylicious is starting").  Googling 'standard terminal widths' seems to suggest that some software still defaults to 80.   So I think it make sense to fly under that width to avoid wrapping in common use-cases.

Could we see a rendering at 50 and 60 for a comparison?

**Comment by insectengine** [comment]
asci_405060_reverse
asci_405060_default
[kroxy_ascii_60.txt](https://github.com/kroxylicious/kroxylicious/files/14223320/kroxy_ascii_60.txt)
[kroxy_ascii_50.txt](https://github.com/kroxylicious/kroxylicious/files/14223321/kroxy_ascii_50.txt)
[kroxy_ascii_40.txt](https://github.com/kroxylicious/kroxylicious/files/14223322/kroxy_ascii_40.txt)

Here is a fresh set at 40, 50, and 60.  I've also included screen captures in light/dark.

**Comment by k-wall** [comment]
thank you @insectengine

+1 to the 60 char.

@gracegrimwood @tombentley @robobario @SamBarker WDYT

**Comment by SamBarker** [comment]
Yeah I think the 60char version is the winner as its the only one that comes close to retaining the croc's smile.

**Review by SamBarker — APPROVED** [review]
LGTM

**Pull request merged**
