### PR TITLE
Setup Sonarcloud connected mode (IDE integration for Intellij) 

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Enhancement / new feature

### Description

The Sonar plugin for IntelliJ has the ability to use rules from project definition in Sonarcloud directly in the IDE.  This configuration can be committed to a project's repo in order to give all the project's developer's the same experience   The feedback the developer gets in the IDE should match the feedback they'll receive from the CI workflow.  That should improve productivity.

As Kroxylicious already as a public organisation as Sonarcloud, [kroxylicious](https://sonarcloud.io/organizations/kroxylicious/projects) and defines project for [kroxylicious](https://sonarcloud.io/project/overview?id=kroxylicious_kroxylicious) and [kroxylicious-junit5-extension](https://sonarcloud.io/project/overview?id=kroxylicious_kroxylicious-junit5-extension), we can benefit from this integration.

https://docs.sonarsource.com/sonarlint/intellij/team-features/connected-mode-setup/#bind-using-shared-configuration

### Additional Context

I've been trying out the IDE integration for a few weeks without noticing any downsides, so I thought it is worth sharing the config.

Here's how it looks for me.

Screenshot 2024-09-07 at 16 47 37

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Review by SamBarker — COMMENTED** [review]
I'm confused by this, I had configured `.idea/sonarlint.xml` outside of version control. Deleting that and restarting idea didn't seem to pickup this file. So I manually configured it again (no `sonarlint.xml`, why?) then I ticked share configuration and the dialog said it would create this file, but having done so I still see no changes...

**Comment by SamBarker** [comment]
Having switched branches I think my intellij was in a bad state as it created a `.connectedMode.json` file this time...

**Comment by k-wall** [comment]
> Having switched branches I think my intellij was in a bad state as it created a `.connectedMode.json` file this time...

Let me see how my laptop reacts to appearance of the `connectedMode.json` file for the first time.

**Comment by k-wall** [comment]
gah, what a horrific UI experience.

From what I can tell it ignored the `connectedMode.json` and then prompted me to create it (with the same content).  I'm baffled

Maybe we ditch this PR and just have some words in the DEVELOPER.md file?

**Comment by SamBarker** [comment]
> gah, what a horrific UI experience.
> 
> From what I can tell it ignored the `connectedMode.json` and then prompted me to create it (with the same content). I'm baffled
> 
> Maybe we ditch this PR and just have some words in the DEVELOPER.md file?

Yikes. I hoped it was just mine install being confused...
Maybe @robobario or @gracegrimwood could give it a test on a clean system and see how they go before we give up on automation?

If they have the same experience adding notes to the Dev guide is a good move.

**Comment by gracegrimwood** [comment]
Apparently I had the plugin installed but never set up, so I gave this a go. I checked out this branch, restarted IntelliJ (that bit is important because it didn't do anything at all before I restarted it), and then it popped up with a message that there was "an existing connected mode configuration file" and asked if I wanted to use it. Once I did that (it asked for a token to set the connection up) it created the following `.idea/sonarlint.xml` file:
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="SonarLintProjectSettings">
    <option name="bindingEnabled" value="true" />
    <option name="projectKey" value="kroxylicious_kroxylicious" />
    <option name="serverId" value="kroxylicious" />
  </component>
</project>
```

So it needs a user token from SonarCloud to get it setup properly, but otherwise that `.sonarlint/connectedMode.json` file works correctly for me. It didn't ask me to recreate it at all.

**Comment by k-wall** [comment]
thanks @gracegrimwood .  it be good to hear @robobario 's experience.

so I suppose we could commit `.idea/sonarlint.xml` too, but we'd need to stipulate a `serverId` in the DEV_GUIDE.md.  We'd also need to check Intellij's behaviour if that server id wasn't present.

**Comment by robobario** [comment]
I got the same popup as Grace, generated a token (logging in with github) and it appears to be applying sonar rules. When I closed IDEA it wrote out the `.idea/sonarlint.xml` same as for Grace:

```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="SonarLintProjectSettings">
    <option name="bindingEnabled" value="true" />
    <option name="projectKey" value="kroxylicious_kroxylicious" />
    <option name="serverId" value="kroxylicious" />
  </component>
</project>
```

**Comment by robobario** [comment]
maybe better to gitignore .idea/sonarlint.xml? The serverId was automatically populated when it popped up the dialogue to connect.

**Comment by k-wall** [comment]
I'll add that ignore to the PR

**Comment by k-wall** [comment]
This just needs a review tick, then I think it is good to merge.

**Pull request merged**
