### PR TITLE
Use fabric8 client BOM for consistent dependency management

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Refactoring

### Description

Use fabric8 client BOM for consistent dependency management.  

Why: the system-test module and strimzi both have dependencies on different parts the fabric8 client project.  Unless the version number is aligned properly, there can be issues at build or runtime (such as https://github.com/fabric8io/kubernetes-client/issues/5617).    Relying on the fabric8 client BOM should impose version consistency.

_Please describe your pull request_

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Comment by k-wall** [comment]
hey @SamBarker and @franvila this replaces #748 .  I *think* this is a better approach

**Review by franvila — APPROVED** [review]

**Comment by k-wall** [comment]
system-tests are passing for me locally with this change.

**Review by SamBarker — COMMENTED** [review]
Cool to see a bom being used, but I'm a little confused why that actually fixes the version conflict with strimzi. Does using the the bom mean maven selects a different version as nearest?

(I don't doubt it fixed the issue just trying to understand why)

**Comment by k-wall** [comment]
> Cool to see a bom being used, but I'm a little confused why that actually fixes the version conflict with strimzi. Does using the the bom mean maven selects a different version as nearest?
> 
> (I don't doubt it fixed the issue just trying to understand why)

I'm sure I don't think a have a perfect mental model for Maven, but I think it works like this.   The fabric8 BOM has `<dependencyManagement/>` dependency declarations for all fabric8 libs, including all those used by Strimzi and Kroxylicious.   So that manages the version of Strimzi's fabric8 dependecies to the same version as we have in our parent POM.  That should avoid the possibility of version inconsistency. 

Steven Hawkins mentioned [in this comment](https://github.com/fabric8io/kubernetes-client/issues/5617#issuecomment-1827901197) that he thought forcing Strimzi to use newer fabric8 dependencies should be okay.  As this is test code, I think it's good enough.

**Pull request merged**
