### PR TITLE
Adding rate rps and rate mips to the performance test producer results

### PR DESCRIPTION
**Pull request by franvila**
### Type of change

- Enhancement / new feature

### Description

Added rate rps and rate mips to the results to have more info about how producer performs.

### Checklist

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Comment by franvila** [comment]
@strimzi-ci run perf

**Comment by franvila** [comment]
@strimzi-ci run perf

**Comment by franvila** [comment]
@strimzi-ci run perf

**Review by k-wall — APPROVED** [review]
lgtm

**Pull request merged**
