### PR TITLE
Ssl timeouts

### LINKED ISSUE #1659: Upstream TLS timeout too short
In [#1650](https://github.com/kroxylicious/kroxylicious/issues/1650#issuecomment-2532906889_), the user noticed that the TLS upstream timeout is rather aggressive (100ms).   The Netty's default is 10,000ms.   

>For your information, I have adapted the [SSL handshake timeout](https://github.com/kroxylicious/kroxylicious/blob/d09869e60edb3349e33cfb44389327641ee24560/kroxylicious-runtime/src/main/java/io/kroxylicious/proxy/internal/KafkaProxyFrontendHandler.java#L484) because 100ms was not enough. 
> Maybe a dedicated conf will be a good fit. 

> _Originally posted by @LGouellec in https://github.com/kroxylicious/kroxylicious/issues/1650#issuecomment-2532906889_
   

We should:

* reconsider if our default is good and/or
* consider if adding configuration to allow the timeout to be tuned is a good idea.

### PR DESCRIPTION
**Pull request by SamBarker**
### Type of change

- Bugfix

### Description

Fixes #1659. Reverts some debugging changes that were missed when merging the State machine.

### Additional Context

The reduced timeout was in service of debugging issues with the state machine and not driven by anything happening in real deployments.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Update documentation
- [ ] Make sure all unit/integration tests pass
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] If applicable to the change, [trigger the system test suite](../blob/main/DEV_GUIDE.md#jenkins-pipeline-for-system-tests).  Make sure tests pass.
- [ ] If applicable to the change, [trigger the performance test suite](../blob/main/PERFORMANCE.md#jenkins-pipeline-for-performance). Ensure that any degradations to performance numbers are understood and justified.
- [ ] Ensure the PR references relevant issue(s) so they are closed on merging.
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

> **_NOTE:_**  You must be a member of `@kroxylicious/developers` to trigger the system test and performance test suites.  If you are not part of this group, comment on the PR requesting a trigger, tagging `@kroxylicious/developers`.

### CODE REVIEW

**Review by robobario — APPROVED** [review]
LGTM, though I wonder do we have some way to test this to prevent regression

Also needs a CHANGELOG entry

**Comment by SamBarker** [comment]
Its a regression on main since the last release, I don't think it merits going in the changelog, does it?

**Comment by robobario** [comment]
import order issue somehow?

**Comment by robobario** [comment]
> Its a regression on main since the last release, I don't think it merits going in the changelog, does it?

sorry, missed that it was unreleased

**Pull request merged**
