### PR TITLE
Remove deprecated EnvelopeEncryption

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Enhancement / new feature

### Description

0.5.0 replaced `EnvelopeEncryption` (introduced at 0.4.0) with `RecordEncryption` retaining `EnvelopeEncryption` for backward compatibility.  It seems reasonable to remove EnvelopeEncryption for the next release.

why now: my work on #1155 prompts me to do this now.  Removing the EnvelopeEncryption helps keep the PRs smaller.

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [x] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [x] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Review by SamBarker — COMMENTED** [review]
I thought we were keeping it for two minor release?

My other thought is now we have json alias support should we add that for the configuration class? I'm not sure it's worth it but wanted to check sentiment.

**Comment by k-wall** [comment]
> I thought we were keeping it for two minor release?

I didn't know that.  If that's what we've decided, fine.  I was just trying to avoid refactor deprecated code.  It turns out the refactoring is less deep.

> My other thought is now we have json alias support should we add that for the configuration class? I'm not sure it's worth it but wanted to check sentiment.

If you are thinking about `@JsonAlias` I don't think that helps.  We'd need something to alias the factory name, wouldn't we?

**Review by SamBarker — APPROVED** [review]
> I didn't know that. If that's what we've decided, fine. I was just trying to avoid refactor deprecated code. It turns out the refactoring is less deep.
If you don't know it, then it wasn't agreed (I could easily be confusing ours with the Flink policy). 

> If you are thinking about @JsonAlias I don't think that helps. We'd need something to alias the factory name, wouldn't we?
I was, and yes your right it would be too limited.

**Comment by SamBarker** [comment]
We do also need to update the TLS integration test

**Comment by k-wall** [comment]
I'll close this pull request, the changes  rippling for #1155 don't really affect it much.

**Pull request closed without merging**
