### PR TITLE
declare metrics port in kubernetes-examples

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Bugfix

### Description

the kroxylicious configs used by the examples already [expose](https://github.com/k-wall/kroxylicious/blob/7ddb17030c67157618cd0db74470d0ea4e3fa0a8/kubernetes-examples/snirouting_tls/base/kroxylicious/kroxylicious-config.yaml#L14) metrics endpoint, but the kubernetes deployments yamls don't actually expose the container port.  There's nothing in the example actually relying on the metrics being available.

either the configs should change to remove the metrics endpoint, or the deployments should declare the port.

having the deployments expose the metrics is useful (it is helped inform #918), so I opt to keep to expose them.

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Comment by robobario** [comment]
The record-encryption example sets a custom metrics port and also wires up a nodeport service as well to make it available on `minikube:30090`. Done as part of adding KMS metrics  #861. This was just a convenience so they are available from the host for adhoc exploration.

I think we should change it to use the default port, remove the service, and add docs showing how to get at the metrics by firing off a curl from within the cluster. This would keep it consistent over all the examples.

**Comment by k-wall** [comment]
@robobario could you re-review please?

**Comment by k-wall** [comment]
@robobario can you review please?

**Review by robobario — APPROVED** [review]
LGTM, thanks Keith

**Pull request merged**
