### PR TITLE
Skip sonar scan during system tests

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Refactoring

### Description

Skip the sonar scan for systemtests (as we do for perf tests)

### Additional Context

why: we're not running system tests with the sonar ci workflow (by design), so there is no coverage
generate for that module.  the lack of coverage is dragging down the stats for the rest of the project.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Comment by SamBarker** [comment]
@franvila and I discussed this during the original system tests PR. We wanted to keep static analysis on the system tests but exclude them from coverage.

I tried to do that with a properties file, hunting it down is beyond me from my phone, so I'm guessing that is not applying as intended.

**Comment by franvila** [comment]
> @franvila and I discussed this during the original system tests PR. We wanted to keep static analysis on the system tests but exclude them from coverage.
> 
> I tried to do that with a properties file, hunting it down is beyond me from my phone, so I'm guessing that is not applying as intended.

Yes, it would be good to have static analysis for system tests code as well, but exclude the coverage. What we did was adding the property `sonar.coverage.exclusions`, but don't know if it is doing what we expected.

**Comment by k-wall** [comment]
I'll take a closer look and see if I can work out what's happening.

**Comment by franvila** [comment]
Last change into the system tests module is skipping the code coverage. I think this is the expected behavior. https://github.com/kroxylicious/kroxylicious/pull/806

**Comment by k-wall** [comment]
> Last change into the system tests module is skipping the code coverage. I think this is the expected behavior. #806

I don't *think* that'll help.

I'm going to close this PR as it is not what we want.

**Pull request closed without merging**
