### PR TITLE
Write all bytes from a byteBuffer in a single shot rather than iterating byte at a time

### PR DESCRIPTION
**Pull request by SamBarker**
### Type of change

- Enhancement / new feature
- Refactoring

### Description

Write all bytes from a byteBuffer in a single shot rather than iterating byte at a time

### Additional Context

More low hanging fruit form #1181 flame graphs.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Review performance test results. Ensure that any degradations to performance numbers are understood and justified.
- [ ] Make sure all Sonarcloud warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Review by k-wall — APPROVED** [review]
lgtm

**Comment by tombentley** [comment]
@SamBarker do you know where the values for the `Previous Value` in the perf results come from? I assume it's not a run taken from the point where the PR's branch diverged from `main`, because the numbers for Previous Value are identical to the ones in yesterdays PR.

**Comment by SamBarker** [comment]
> @SamBarker do you know where the values for the Previous Value in the perf results come from? I assume it's not a run taken from the point where the PR's branch diverged from main, because the numbers for Previous Value are identical to the ones in yesterdays PR.

No I don't I think it was just the last completed build. Given the environments I don't believe runs are comparable but previous is useful for comparing how the various scenarios compare within a run. So we can't compare `05-envelope-encryption-filter-no-encrypt` between runs be we can compare `01-no-proxy-baseline` with `05-envelope-encryption-filter-no-encrypt` within each run.

**Comment by tombentley** [comment]
If the `Previous Value` is not based on "the code directly before the commits in this PR" (which I don't think it can be, given that the values above are identical to those in the PR we merged yesterday, so I assume they must be take from the same historical benchmark run) then I don't know how to interpret the numbers within a given row. 

```
   +   Some commit in the past: Previous value = 10
   |
   + ...
   |
   +   Yesterdays changes: Current value = 5
   |
   +   This PR, Current value = 8
 ```

When reviewing this PR we're comparing 8 with 10, seeing it's smaller and (incorrectly) interfering that this PR is making the value 2 smaller. In actual fact the effect of this PR is that it's making the value 3 bigger. 

Am I missing something?

**Comment by SamBarker** [comment]
> Am I missing something?

No, your not missing anything. Results between runs are not directly comparable. Even if they could come from the branching point they still wouldn't be comparable as we don't have control of the host hardware or neighbouring load. Thats why I say we can only compare results within a run. So we can compare the costs of encryption with the costs of no filters within a the current run and we can look at that comparison in the previous run to see if we improved the differential but we **can not** compare between current and previous.

**Comment by k-wall** [comment]
@franvila ^ I thought you said that the performance tests run on the same class of hardware?   Is that right?

**Comment by franvila** [comment]
> @franvila ^ I thought you said that the performance tests run on the same class of hardware? Is that right?

Yes, all performance Jenkins jobs are configured in the same way. I'm a little bit surprised as well why PR and merge have so different results. Obviously if this is the normal behavior they cannot be comparable at all.

This is the current behavior of performance runs:
- Every time `@strimzi-ci run perf` is written as a comment the PR job is launched using this resources (dedicated in Openstack):  # ci.standard.xxl (12vCPUs, 24GB RAM, 120GB Disc)
- Once the PR is merged, the Merge job is launched using the same resources (dedicated in Openstack):  # ci.standard.xxl (12vCPUs, 24GB RAM, 120GB Disc). The merge request stores the result in [kibana](http://kibana.intlab.perf-infra.lab.eng.rdu2.redhat.com/app/dashboards#/view/3f4313d0-3033-11ee-9cee-f1d5c307361a) and in the latest successful run. Those results are used in the previous column of the PR comment.

About what happened with PRs 1190 and 1192, the results are the same because the executions were done only with 2 hours of difference and it was not enough for the merge run to finish.

**Review by franz1981 — COMMENTED** [review]
Lovely 😍

**Pull request merged**
