### PR TITLE
Install a2s in the asciidoc workflow

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

_Select the type of your PR_

- Documentation

### Description

* Install [(Go 1.20)](https://github.com/marketplace/actions/setup-go-environment). Action should set GOBIN as side-effect.
* Build and install the a2s (should install to `GOBIN`)
* a2s should be on the path for asciidoctor to find.

Require so the diagrams being added by #406 are pretty.

### Additional Context

_Why are you making this pull request?_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Make sure all Sonar-Lint warnings are addressed or are justifiably ignored.
- [ ] Update documentation
- [ ] Reference relevant issue(s) and close them after merging
- [ ] For user facing changes, update CHANGELOG.md (remember to include changes affecting the API of the test artefacts too).

### CODE REVIEW

**Comment by robobario** [comment]
Had a bit of a battle to get a2s working :)

`manoelcampos/asciidoctor-ghpages-action@v2` uses a docker container to do the build, so installing golang and a2s on the host didn't help.

I got it going with:

```
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          source_dir: docs/
          pre_build: "apk add go && go install github.com/asciitosvg/asciitosvg/cmd/a2s@latest && cp ~/go/bin/a2s /usr/local/bin/"
          asciidoctor_params: "-r asciidoctor-diagram"
          post_build: 'find . -name "*.svg" -exec git add -f {} \;'
```

So before the build install go and a2s and put it on the path (the pre_build is [executed with eval](https://github.com/manoelcampos/asciidoctor-ghpages-action/blob/630d76cde7a82810ff6f8de79acffadb9edac9da/entrypoint.sh#L71) so I don't think we can update the PATH from in there, so I've shuffled the binary to /usr/local/bin)

Then to activate asciidoctors diagram module you need to add the `-r asciidoctor-diagram` ([docs](https://github.com/asciidoctor/docker-asciidoctor/tree/main#how-to-use-it)) to the `asciidoctor` call.

And afterwards, by default it's only adding *.html files to the `gh-pages` branch so we need a post_build call to git add the svgs.

Github pages wasn't deploying nicely on my fork for some reason but I checked out https://github.com/robobario/kproxy/tree/gh-pages locally and it looks good.

**Comment by k-wall** [comment]
@robobario thank you so much for the time you've put into getting this working.

**Comment by k-wall** [comment]
Output reviewed on Rob's branch - SVGs look correct.

**Comment by k-wall** [comment]
(raised https://github.com/asciidoctor/docker-asciidoctor/pull/372 is get rid of the tech debt)

**Review by robobario — APPROVED** [review]
LGTM

**Pull request merged**
