### PR TITLE
Use java 19 everywhere

### PR DESCRIPTION
**Pull request by robobario**
### Type of change

- Enhancement / new feature

### Description

Use java 19 as target and language level.

### Additional Context

Software currency. We know there is some performance issue with netty 4 and JDK 17, this PR is to test the waters and see if there is anything that leaps out in our performance benchmark.

### CODE REVIEW

**Comment by robobario** [comment]
Results from perf test:

Possible performance regression was detected for benchmark **'kafka producer perf test Benchmark'**.
Benchmark result of this commit is worse than the previous benchmark result exceeding threshold `1.50`.

| Benchmark suite | Current: d096dab2d21cc5195df06c7b25188618213a2cbc | Previous: d331499423b49effe0e98c413319f1665407f8b6 | Ratio |
|-|-|-|-|
| `AVG Latency` | `172.09` ms | `10.5` ms | `16.39` |
| `95th Latency` | `671` ms | `4` ms | `167.75` |
| `99th Latency` | `804` ms | `479` ms | `1.68` |

**Comment by SamBarker** [comment]
What JDK were the perf tests run with? Was that JDK 19?

**Comment by robobario** [comment]
> What JDK were the perf tests run with? Was that JDK 19?

Yep, [19 zulu](https://github.com/kroxylicious/kroxylicious/blob/d096dab2d21cc5195df06c7b25188618213a2cbc/.github/workflows/performance.yml#L41).

**Comment by robobario** [comment]
I ran some basic perf tests as laid out in the `benchmarking.md` locally to make sure they were run on same hardware. I also ran with a slight variation using a fixed message from file instead of random data.

## Randomised 1024 bytes messages from the kafka producer test client

```bash
 bin/kafka-producer-perf-test.sh \
    --topic perf-test \
    --throughput -1 \
    --num-records 10000000 \
    --record-size 1024 \
    --producer-props acks=all bootstrap.servers=localhost:9192
```

| case  | records/sec | avg latency | max latency | 50th| 95th | 99th | 99.9th |
| ------------- | ----|-------------|-------------|-----|-----|------|---------|
| direct to kafka | 85822|1.74ms|232.00 ms|0 ms|1ms|50ms|191ms|
| java 11 runtime at proxy | 86772|2.20 ms|469.00 ms|0ms|1ms|64ms|223ms|
| java 19 runtime at proxy | 87765|2.54 ms|252.00 ms|0 ms|1 ms|99 ms|217 ms|

## Fixed 1024 byte messages from the kafka producer test client

```python
with open("out", "w") as f:
  f.write("a" * 1024)
```

```bash
bin/kafka-producer-perf-test.sh \
    --topic perf-test \
    --throughput -1 \
    --num-records 10000000 \
    --producer-props acks=all bootstrap.servers=localhost:9192 \
    --payload-delimiter , \
    --payload-file out
```

| case  | records/sec | avg latency | max latency | 50th| 95th | 99th | 99.9th |
| ------------- | ----|-------------|-------------|-----|-----|------|---------|
| direct to kafka | 219178|138.88 ms|396.00 ms|130 ms|171 ms|376 ms|392 ms|
| java 11 runtime at proxy| 202486|150.34 ms|464.00 ms|142 ms|174 ms|396 ms|453 ms|
| java 19 runtime at proxy| 212670|142.78 ms|403.00 ms|135 ms|180 ms|367 ms|396 ms|

machine specs:
```
Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Dell XPS
```

**Comment by robobario** [comment]
Closing in favour of: https://github.com/kroxylicious/kroxylicious/pull/197

**Pull request closed without merging**
